In [1]:
#pip install pandas

In [2]:
#pip install numpy

In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
hall=pd.read_csv('data.csv')

In [3]:
df=hall.copy()

In [4]:
df= df[df['place']=='콘서트홀']

In [5]:
pd.set_option('display.max_columns', None)

In [7]:
df['seat'].unique().tolist()

['3층 BOX9 10',
 '1층 B블록12열 7',
 '1층 A블록2열 1',
 '3층 E블록4열 8',
 '2층 D블록8열 4',
 '1층 C블록17열 3',
 '3층 BOX9 5',
 '3층 BOX12 3',
 '2층 D블록8열 3',
 '1층 C블록2열 2',
 '2층 E블록3열 16',
 '2층 BOX2 2',
 '1층 C블록20열 4',
 '1층 D블록10열 8',
 '1층 B블록7열 7',
 '3층 G블록5열 8',
 '1층 B블록21열 9',
 '1층 B블록17열 4',
 '1층 D블록18열 6',
 '3층 M블록1열 2',
 '1층 C블록15열 8',
 '1층 B블록3열 7',
 '3층 F블록5열 5',
 '1층 E블록17열 1',
 '1층 D블록7열 11',
 '1층 D블록22열 3',
 '3층 G블록1열 5',
 '1층 C블록4열 6',
 '1층 B블록7열 5',
 '1층 E블록19열 3',
 '3층 F블록4열 3',
 '1층 C블록6열 7',
 '2층 C블록7열 7',
 '2층 A블록4열 7',
 '1층 A블록8열 1',
 '1층 B블록16열 6',
 '1층 C블록1열 10',
 '3층 D블록7열 13',
 '1층 A블록15열 4',
 '1층 B블록14열 11',
 '1층 C블록6열 13',
 '1층 A블록21열 5',
 '2층 E블록3열 13',
 '1층 B블록18열 11',
 '1층 D블록13열 3',
 '3층 G블록3열 2',
 '1층 B블록13열 11',
 '합창석 G블록2열 24',
 '1층 C블록1열 4',
 '2층 E블록2열 4',
 '1층 E블록6열 2',
 '3층 F블록6열 6',
 '3층 BOX11 5',
 '1층 C블록19열 8',
 '3층 D블록7열 3',
 '1층 A블록11열 7',
 '1층 C블록8열 4',
 '1층 E블록17열 10',
 '1층 D블록12열 2',
 '1층 D블록5열 10',
 '1층 E블록15열 5',
 '2층 B블록1열 4',
 '1층 D블록12열 5',
 '1층 D블록21열 5',
 '2층 E블록6열 13',
 '1층 C블록12열 3',
 '1층 C블록12열 10',
 '1층 C블록3열 6',
 '3층 E블록7열 10',
 '3층 E블록5열 3',
 '1층 D블록6열 1',
 '2층 E블록4열 6',
 '1층 A블록16열 8',
 '1층 E블록18열 3',
 '1층 C블록2열 6',
 '3층 A블록4열 14',
 '2층 A블록5열 6',
 '2층 E블록2열 3',
 '1층 B블록19열 12',
 '2층 B블록1열 9',
 '2층 BOX3 3',
 '1층 E블록21열 5',
 '3층 BOX11 8',
 '1층 C블록5열 5',
 '1층 D블록9열 5',
 '1층 D블록9열 2',
 '1층 A블록1열 7',
 '1층 C블록19열 4',
 '1층 D블록15열 11',
 '1층 E블록22열 6',
 '3층 G블록6열 4',
 '2층 E블록3열 18',
 '2층 B블록3열 8',
 '3층 A블록3열 3',
 '1층 E블록13열 2',
 '1층 D블록11열 12',
 '1층 C블록14열 8',
 '1층 C블록4열 10',
 '1층 A블록21열 2',
 '1층 B블록21열 11',
 '3층 N블록1열 1',
 '1층 E블록11열 8',
 '2층 BOX2 6',
 '2층 A블록7열 10',
 '1층 B블록10열 4',
 '1층 E블록2열 4',
 '1층 A블록6열 9',
 '1층 B블록17열 9',
 '1층 E블록10열 7',
 '1층 A블록18열 10',
 '3층 D블록5열 6',
 '2층 C블록7열 12',
 '합창석 G블록3열 9',
 '1층 A블록11열 10',
 '1층 D블록22열 10',
 '1층 E블록15열 11',
 '2층 A블록6열 8',
 '1층 E블록9열 4',
 '1층 D블록6열 7',
 '2층 C블록2열 3',
 '1층 B블록8열 2',
 '1층 B블록9열 6',
 '1층 C블록7열 10',
 '1층 E블록7열 9',
 '2층 E블록6열 2',
 '3층 M블록1열 12',
 '합창석 H블록3열 9',
 '1층 B블록14열 8',
 '3층 F블록6열 7',
 '1층 D블록16열 1',
 '1층 C블록13열 12',
 '1층 B블록1열 5',
 '1층 A블록12열 10',
 '1층 B블록1열 7',
 '합창석 H블록3열 13',
 '2층 B블록7열 6',
 '1층 D블록10열 5',
 '1층 A블록10열 8',
 '3층 A블록2열 3',
 '2층 E블록7열 2',
 '1층 B블록11열 4',
 '1층 E블록12열 2',
 '1층 A블록18열 1',
 '1층 A블록7열 10',
 '1층 C블록4열 3',
 '1층 D블록22열 1',
 '2층 A블록1열 9',
 '1층 A블록5열 1',
 '2층 E블록3열 11',
 '1층 E블록21열 3',
 '1층 E블록15열 1',
 '2층 A블록3열 15',
 '2층 A블록4열 11',
 '2층 A블록6열 18',
 '2층 E블록7열 5',
 '1층 B블록14열 12',
 '2층 E블록6열 18',
 '1층 B블록20열 7',
 '1층 C블록9열 5',
 '1층 E블록13열 6',
 '3층 E블록7열 1',
 '2층 B블록5열 7',
 '1층 E블록7열 1',
 '1층 D블록13열 6',
 '2층 A블록5열 19',
 '2층 E블록3열 10',
 '1층 B블록8열 10',
 '1층 D블록3열 5',
 '2층 D블록5열 4',
 '1층 E블록21열 6',
 '2층 B블록4열 5',
 '1층 A블록12열 9',
 '2층 C블록4열 11',
 '2층 C블록6열 1',
 '1층 A블록5열 2',
 '1층 E블록8열 8',
 '1층 B블록16열 9',
 '2층 BOX5 3',
 '합창석 H블록4열 6',
 '1층 B블록17열 7',
 '2층 E블록4열 13',
 '1층 A블록6열 6',
 '1층 B블록5열 8',
 '3층 C블록6열 12',
 '1층 C블록17열 2',
 '1층 E블록6열 5',
 '1층 D블록13열 9',
 '3층 E블록6열 12',
 '합창석 G블록3열 13',
 '2층 D블록7열 1',
 '1층 C블록18열 2',
 '1층 D블록9열 10',
 '합창석 F블록3열 3',
 '합창석 G블록4열 14',
 '3층 C블록6열 5',
 '2층 D블록6열 12',
 '1층 B블록8열 11',
 '3층 M블록1열 4',
 '1층 A블록5열 5',
 '1층 D블록11열 4',
 '1층 B블록5열 10',
 '2층 D블록6열 7',
 '1층 E블록10열 1',
 '1층 B블록6열 9',
 '2층 C블록4열 1',
 '1층 D블록14열 6',
 '1층 E블록8열 6',
 '1층 B블록2열 8',
 '1층 B블록3열 10',
 '3층 A블록4열 1',
 '1층 C블록4열 5',
 '1층 D블록6열 3',
 '합창석 G블록4열 37',
 '1층 D블록22열 13',
 '3층 D블록6열 7',
 '1층 C블록11열 4',
 '1층 B블록19열 5',
 '1층 C블록11열 5',
 '2층 E블록1열 2',
 '3층 A블록6열 1',
 '1층 D블록17열 7',
 '3층 M블록1열 11',
 '1층 A블록11열 2',
 '2층 C블록4열 12',
 '1층 E블록7열 7',
 '3층 D블록5열 12',
 '3층 E블록4열 9',
 '1층 A블록22열 1',
 '1층 E블록21열 1',
 '1층 C블록10열 10',
 '2층 D블록6열 5',
 '1층 C블록6열 8',
 '3층 G블록4열 14',
 '1층 C블록16열 5',
 '1층 E블록16열 8',
 '1층 B블록16열 2',
 '1층 C블록13열 13',
 '1층 A블록17열 4',
 '1층 B블록16열 12',
 '1층 D블록17열 8',
 '1층 B블록14열 10',
 '1층 D블록14열 4',
 '합창석 G블록4열 16',
 '1층 C블록11열 9',
 '2층 E블록5열 16',
 '1층 C블록11열 13',
 '1층 A블록6열 10',
 '1층 E블록1열 7',
 '1층 B블록22열 2',
 '1층 E블록3열 7',
 '3층 G블록2열 3',
 '1층 C블록1열 9',
 '3층 A블록6열 7',
 '2층 C블록1열 5',
 '2층 B블록2열 2',
 '2층 A블록4열 3',
 '1층 C블록21열 3',
 '1층 B블록3열 3',
 '합창석 F블록3열 12',
 '1층 A블록1열 2',
 '1층 D블록12열 7',
 '2층 BOX1 1',
 '합창석 G블록2열 14',
 '3층 C블록4열 4',
 '1층 D블록8열 10',
 '2층 D블록2열 3',
 '2층 A블록4열 2',
 '1층 E블록8열 3',
 '3층 D블록4열 11',
 '합창석 G블록2열 21',
 '1층 D블록18열 3',
 '1층 B블록11열 6',
 '1층 C블록10열 1',
 '1층 D블록6열 5',
 '3층 C블록6열 1',
 '1층 D블록16열 8',
 '1층 B블록1열 1',
 '2층 D블록7열 13',
 '1층 B블록7열 11',
 '합창석 F블록4열 2',
 '1층 A블록21열 4',
 '1층 B블록13열 10',
 '1층 D블록4열 8',
 '1층 A블록11열 4',
 '3층 B블록7열 2',
 '1층 C블록17열 14',
 '1층 A블록16열 10',
 '1층 C블록16열 4',
 '3층 F블록6열 4',
 '1층 A블록15열 1',
 '2층 B블록5열 1',
 '2층 C블록7열 1',
 '2층 E블록3열 9',
 '1층 C블록20열 13',
 '3층 C블록4열 5',
 '2층 E블록5열 9',
 '3층 F블록6열 8',
 '합창석 G블록1열 1',
 '1층 A블록3열 4',
 '3층 M블록1열 9',
 '2층 A블록5열 9',
 '1층 A블록13열 11',
 '1층 B블록9열 10',
 '1층 C블록7열 7',
 '2층 E블록6열 15',
 '3층 G블록5열 5',
 '1층 B블록18열 12',
 '1층 C블록19열 5',
 '1층 A블록15열 3',
 '합창석 H블록1열 12',
 '2층 A블록3열 10',
 '2층 BOX6 1',
 '합창석 F블록2열 5',
 '1층 B블록5열 7',
 '3층 E블록7열 4',
 '1층 D블록16열 6',
 '2층 A블록3열 1',
 '2층 A블록5열 5',
 '3층 G블록6열 1',
 '1층 D블록21열 11',
 '3층 A블록6열 6',
 '3층 D블록6열 5',
 '1층 E블록22열 3',
 '1층 C블록2열 4',
 '1층 D블록22열 2',
 '3층 B블록6열 4',
 '1층 D블록17열 1',
 '2층 B블록1열 7',
 '1층 B블록7열 6',
 '1층 B블록10열 10',
 '1층 D블록7열 5',
 '1층 C블록21열 9',
 '2층 A블록6열 12',
 '1층 A블록12열 8',
 '2층 A블록2열 14',
 '3층 F블록5열 7',
 '2층 B블록6열 5',
 '1층 B블록9열 1',
 '1층 C블록19열 2',
 '합창석 F블록2열 13',
 '1층 B블록12열 9',
 '1층 D블록2열 10',
 '3층 E블록6열 6',
 '2층 E블록5열 1',
 '합창석 G블록2열 12',
 '1층 E블록10열 4',
 '1층 A블록15열 10',
 '3층 M블록2열 13',
 '2층 E블록7열 15',
 '1층 E블록7열 3',
 '1층 A블록9열 8',
 '1층 C블록17열 9',
 '1층 C블록8열 12',
 '1층 C블록16열 8',
 '2층 A블록2열 9',
 '합창석 H블록1열 14',
 '2층 A블록1열 15',
 '1층 C블록2열 9',
 '2층 E블록5열 2',
 '1층 B블록10열 11',
 '2층 E블록7열 16',
 '1층 D블록1열 9',
 '1층 C블록21열 15',
 '1층 C블록15열 11',
 '2층 A블록2열 10',
 '2층 D블록6열 2',
 '1층 C블록15열 13',
 '1층 B블록17열 5',
 '1층 B블록13열 5',
 '1층 B블록21열 8',
 '1층 C블록17열 5',
 '2층 A블록6열 13',
 '2층 C블록4열 8',
 '3층 E블록6열 11',
 '2층 C블록3열 4',
 '3층 E블록5열 9',
 '1층 B블록15열 2',
 '1층 C블록4열 1',
 '1층 A블록1열 1',
 '1층 A블록21열 7',
 '3층 C블록6열 8',
 '2층 A블록8열 7',
 '1층 D블록20열 4',
 '3층 G블록7열 5',
 '1층 B블록8열 1',
 '1층 C블록3열 2',
 '2층 B블록7열 3',
 '1층 C블록16열 12',
 '1층 E블록10열 10',
 '1층 E블록8열 1',
 '합창석 G블록1열 19',
 '1층 C블록9열 11',
 '1층 C블록4열 7',
 '2층 BOX5 7',
 '2층 E블록4열 8',
 '2층 A블록6열 17',
 '1층 C블록16열 10',
 '1층 E블록20열 3',
 '1층 B블록12열 1',
 '1층 C블록3열 3',
 '1층 D블록19열 5',
 '1층 E블록11열 9',
 '3층 BOX9 7',
 '1층 C블록8열 2',
 '1층 D블록1열 1',
 '1층 E블록12열 8',
 '3층 D블록7열 7',
 '1층 A블록4열 10',
 '1층 B블록15열 8',
 '3층 C블록4열 8',
 '1층 C블록12열 13',
 '합창석 G블록4열 25',
 '1층 D블록2열 2',
 '1층 A블록8열 6',
 '1층 B블록15열 12',
 '1층 D블록14열 3',
 '1층 D블록20열 13',
 '1층 C블록4열 2',
 '1층 B블록20열 11',
 '2층 B블록8열 4',
 '2층 A블록1열 12',
 '1층 B블록20열 1',
 '2층 A블록4열 14',
 '1층 A블록13열 12',
 '2층 E블록5열 10',
 '1층 C블록15열 6',
 '2층 A블록7열 6',
 '2층 D블록6열 13',
 '2층 A블록8열 3',
 '2층 E블록7열 14',
 '1층 B블록2열 7',
 '합창석 G블록1열 25',
 '1층 B블록1열 8',
 '1층 C블록16열 15',
 '2층 BOX3 8',
 '1층 C블록5열 6',
 '2층 A블록6열 11',
 '1층 A블록17열 1',
 '2층 BOX2 8',
 '1층 A블록15열 12',
 '1층 D블록17열 5',
 '1층 D블록16열 2',
 '1층 B블록4열 2',
 '1층 A블록9열 7',
 '1층 B블록1열 6',
 '1층 C블록1열 2',
 '2층 A블록1열 16',
 '1층 B블록20열 8',
 '1층 D블록17열 4',
 '3층 BOX11 7',
 '1층 D블록7열 10',
 '2층 BOX4 8',
 '2층 B블록1열 8',
 '3층 F블록5열 6',
 '2층 BOX4 6',
 '1층 B블록8열 7',
 '2층 E블록3열 1',
 '3층 E블록7열 12',
 '3층 E블록7열 2',
 '1층 E블록9열 11',
 '1층 E블록4열 3',
 '1층 D블록2열 3',
 '2층 D블록4열 1',
 '3층 F블록6열 2',
 '1층 C블록18열 8',
 '1층 B블록5열 3',
 '1층 E블록6열 1',
 '합창석 G블록4열 33',
 '3층 D블록7열 10',
 '1층 C블록1열 3',
 '3층 D블록5열 7',
 '합창석 G블록1열 13',
 '2층 C블록4열 6',
 '1층 C블록11열 7',
 '2층 D블록5열 2',
 '1층 D블록14열 10',
 '1층 E블록5열 8',
 '1층 B블록22열 9',
 '1층 B블록4열 3',
 '1층 D블록15열 3',
 '1층 C블록3열 9',
 '2층 C블록6열 12',
 '1층 D블록22열 7',
 '3층 N블록1열 6',
 '2층 B블록6열 10',
 '1층 D블록15열 5',
 '1층 D블록18열 2',
 '1층 E블록17열 2',
 '합창석 F블록3열 11',
 '3층 C블록5열 6',
 '1층 B블록8열 5',
 '1층 C블록1열 11',
 '3층 D블록6열 6',
 '3층 A블록5열 12',
 '2층 B블록7열 7',
 '1층 C블록5열 8',
 '1층 B블록22열 8',
 '1층 D블록8열 4',
 '3층 E블록5열 1',
 '1층 E블록9열 5',
 '1층 D블록1열 6',
 '3층 C블록7열 9',
 '1층 D블록22열 12',
 '2층 A블록7열 11',
 '1층 C블록13열 1',
 '1층 E블록17열 4',
 '2층 A블록5열 17',
 '1층 E블록21열 7',
 '2층 E블록1열 15',
 '3층 C블록4열 2',
 '1층 A블록20열 5',
 '1층 C블록20열 15',
 '1층 C블록14열 6',
 '합창석 F블록1열 5',
 '3층 E블록5열 6',
 '합창석 G블록2열 13',
 '1층 D블록21열 6',
 '1층 D블록17열 9',
 '2층 B블록2열 1',
 '2층 C블록2열 9',
 '1층 E블록12열 3',
 '2층 E블록5열 12',
 '2층 C블록1열 11',
 '1층 D블록13열 8',
 '1층 B블록17열 6',
 '3층 A블록5열 11',
 '1층 A블록12열 11',
 '1층 A블록8열 10',
 '1층 D블록19열 3',
 '2층 A블록2열 15',
 '1층 B블록8열 8',
 '2층 BOX5 6',
 '2층 A블록4열 5',
 '1층 C블록7열 6',
 '3층 N블록1열 13',
 '3층 E블록6열 9',
 '1층 C블록13열 10',
 '1층 C블록3열 5',
 '1층 A블록9열 5',
 '2층 D블록1열 3',
 '1층 D블록10열 10',
 '2층 B블록5열 12',
 '2층 E블록4열 12',
 '1층 B블록19열 2',
 '1층 B블록12열 2',
 '2층 E블록4열 10',
 '1층 A블록17열 11',
 '2층 E블록5열 4',
 '1층 D블록8열 3',
 '2층 D블록2열 4',
 '2층 E블록7열 11',
 '1층 C블록20열 5',
 '2층 E블록2열 16',
 '1층 D블록10열 11',
 '1층 B블록16열 5',
 '1층 C블록10열 12',
 '1층 D블록14열 5',
 '2층 C블록2열 8',
 '2층 B블록4열 3',
 '1층 B블록6열 4',
 '3층 G블록1열 4',
 '1층 C블록12열 4',
 '3층 C블록6열 10',
 '2층 C블록2열 6',
 '합창석 F블록1열 2',
 '2층 BOX3 5',
 '1층 C블록10열 8',
 '3층 G블록3열 4',
 '3층 BOX9 4',
 '3층 B블록5열 5',
 '2층 D블록5열 9',
 '합창석 F블록3열 19',
 '1층 E블록11열 11',
 '1층 D블록3열 8',
 '3층 N블록1열 12',
 '3층 A블록1열 2',
 '3층 G블록5열 1',
 '1층 E블록12열 6',
 '3층 F블록4열 2',
 '1층 C블록13열 14',
 '2층 D블록6열 6',
 '2층 A블록5열 12',
 '2층 E블록7열 13',
 '1층 D블록18열 10',
 '3층 E블록4열 4',
 '3층 N블록1열 7',
 '2층 D블록7열 4',
 '3층 C블록7열 2',
 '3층 G블록3열 5',
 '2층 B블록2열 5',
 '1층 D블록14열 9',
 '2층 D블록2열 5',
 '1층 C블록15열 10',
 '2층 BOX4 10',
 '2층 A블록2열 18',
 '1층 B블록16열 4',
 '합창석 G블록4열 31',
 '2층 B블록7열 5',
 '1층 E블록10열 6',
 '2층 D블록1열 4',
 '2층 B블록3열 9',
 '2층 A블록1열 14',
 '2층 BOX2 7',
 '1층 B블록10열 2',
 '1층 D블록3열 10',
 '1층 D블록22열 5',
 '2층 C블록7열 13',
 '3층 A블록4열 8',
 '1층 B블록11열 12',
 '2층 E블록1열 4',
 '1층 B블록17열 11',
 '1층 A블록20열 2',
 '1층 D블록19열 10',
 '3층 F블록4열 1',
 '2층 E블록1열 9',
 '1층 B블록15열 5',
 '1층 C블록2열 12',
 '1층 A블록13열 3',
 '2층 BOX4 7',
 '1층 A블록4열 9',
 '3층 D블록5열 2',
 '1층 C블록8열 10',
 '1층 B블록20열 14',
 '2층 A블록1열 2',
 '2층 D블록1열 8',
 '1층 B블록3열 2',
 '1층 D블록11열 1',
 '1층 D블록2열 9',
 '1층 B블록5열 4',
 '1층 A블록12열 12',
 '합창석 H블록2열 19',
 '1층 B블록12열 11',
 '1층 B블록18열 13',
 '1층 C블록10열 4',
 '2층 C블록5열 7',
 '1층 E블록16열 4',
 '2층 A블록7열 16',
 '3층 F블록4열 7',
 '2층 B블록5열 10',
 '1층 E블록3열 2',
 '1층 C블록7열 13',
 '2층 BOX1 6',
 '1층 E블록4열 10',
 '합창석 F블록1열 14',
 '2층 A블록4열 13',
 '3층 BOX9 2',
 '2층 B블록3열 5',
 '3층 G블록4열 6',
 '1층 C블록18열 10',
 '1층 B블록15열 6',
 '1층 D블록17열 13',
 '1층 B블록13열 3',
 '1층 D블록5열 3',
 '3층 C블록5열 5',
 '1층 B블록16열 11',
 '1층 B블록20열 12',
 '1층 C블록21열 16',
 '2층 E블록6열 4',
 '1층 C블록20열 8',
 '1층 E블록4열 8',
 '1층 A블록2열 7',
 '1층 B블록18열 10',
 '2층 E블록6열 16',
 '2층 B블록8열 3',
 '합창석 H블록1열 10',
 '1층 D블록19열 2',
 '2층 E블록1열 14',
 '3층 F블록5열 2',
 '1층 C블록9열 7',
 '1층 A블록11열 1',
 '1층 C블록3열 12',
 '1층 B블록15열 4',
 '1층 E블록18열 9',
 '1층 D블록19열 12',
 '2층 E블록1열 10',
 '2층 C블록7열 2',
 '2층 E블록4열 5',
 '1층 B블록4열 6',
 '1층 D블록2열 1',
 '2층 BOX5 1',
 '2층 E블록4열 18',
 '1층 E블록6열 7',
 '3층 B블록5열 2',
 '2층 A블록6열 19',
 '2층 A블록2열 17',
 '1층 B블록13열 6',
 '1층 C블록3열 7',
 '3층 A블록6열 2',
 '1층 D블록5열 5',
 '합창석 G블록3열 16',
 '1층 A블록7열 3',
 '3층 B블록7열 4',
 '1층 B블록11열 5',
 '합창석 F블록2열 7',
 '3층 B블록6열 8',
 '1층 E블록1열 3',
 '합창석 F블록2열 4',
 '1층 D블록13열 1',
 '2층 D블록5열 7',
 '2층 C블록3열 2',
 '1층 A블록12열 6',
 '합창석 F블록1열 8',
 '1층 A블록16열 11',
 '2층 A블록2열 8',
 '1층 A블록11열 8',
 '2층 A블록5열 1',
 '1층 B블록9열 5',
 '1층 E블록7열 5',
 '합창석 F블록4열 12',
 '1층 E블록9열 8',
 '1층 D블록19열 1',
 '1층 A블록18열 3',
 '1층 C블록19열 15',
 '1층 E블록9열 2',
 '1층 B블록15열 7',
 '1층 B블록10열 6',
 '1층 B블록13열 1',
 '1층 B블록21열 10',
 '1층 B블록17열 10',
 '3층 E블록6열 1',
 '1층 D블록11열 10',
 '합창석 H블록2열 4',
 '3층 M블록1열 14',
 '1층 D블록3열 4',
 '2층 A블록7열 5',
 '3층 B블록6열 1',
 '합창석 F블록4열 8',
 '1층 C블록15열 7',
 '2층 C블록1열 6',
 '1층 B블록5열 9',
 '1층 A블록12열 1',
 '2층 C블록4열 2',
 '1층 B블록10열 9',
 '2층 BOX3 2',
 '1층 D블록1열 7',
 '1층 C블록4열 9',
 '1층 E블록11열 2',
 '2층 A블록2열 11',
 '1층 D블록15열 2',
 '1층 E블록16열 10',
 '1층 C블록9열 12',
 '1층 E블록12열 12',
 '1층 D블록5열 6',
 '3층 G블록6열 3',
 '3층 E블록6열 3',
 '1층 A블록10열 10',
 '2층 C블록7열 4',
 '3층 BOX7 2',
 '1층 D블록21열 14',
 '합창석 G블록2열 28',
 '합창석 H블록1열 15',
 '1층 B블록11열 10',
 '1층 A블록8열 7',
 '2층 C블록3열 5',
 '1층 C블록6열 5',
 '1층 B블록4열 7',
 '합창석 F블록4열 3',
 '합창석 G블록4열 20',
 '1층 B블록1열 2',
 '1층 E블록5열 5',
 '1층 B블록2열 1',
 '합창석 H블록1열 13',
 '2층 C블록7열 3',
 '1층 C블록12열 2',
 '3층 D블록4열 9',
 '1층 C블록19열 11',
 '1층 E블록11열 7',
 '2층 B블록4열 10',
 '1층 D블록11열 3',
 '1층 C블록2열 11',
 '3층 B블록4열 1',
 '1층 D블록4열 2',
 '1층 C블록9열 6',
 '3층 N블록2열 4',
 '1층 E블록4열 1',
 '1층 E블록20열 2',
 '1층 D블록14열 8',
 '합창석 G블록1열 5',
 '3층 A블록4열 13',
 '3층 C블록4열 6',
 '2층 A블록7열 14',
 '3층 D블록7열 2',
 '2층 E블록5열 14',
 '1층 B블록15열 11',
 '2층 E블록5열 3',
 '1층 E블록7열 2',
 '합창석 H블록4열 12',
 '3층 G블록6열 5',
 '1층 C블록18열 11',
 '3층 N블록2열 8',
 '1층 D블록15열 8',
 '2층 D블록5열 6',
 '3층 C블록6열 2',
 '1층 D블록20열 11',
 '1층 B블록20열 6',
 '1층 C블록16열 6',
 '1층 E블록16열 7',
 '1층 B블록7열 3',
 '1층 B블록22열 7',
 '3층 BOX8 8',
 '3층 B블록7열 8',
 '1층 B블록14열 2',
 '1층 B블록7열 9',
 '2층 C블록3열 9',
 '2층 E블록6열 1',
 '1층 E블록7열 4',
 '합창석 H블록1열 16',
 '1층 D블록8열 7',
 '1층 C블록6열 3',
 '1층 B블록12열 12',
 '3층 A블록3열 2',
 '2층 B블록2열 3',
 '1층 D블록13열 4',
 '1층 D블록7열 4',
 '1층 A블록9열 6',
 '1층 A블록1열 5',
 '1층 D블록21열 10',
 '1층 C블록3열 10',
 '2층 A블록2열 16',
 '3층 E블록4열 3',
 '1층 B블록12열 5',
 '2층 A블록5열 18',
 '1층 C블록3열 8',
 '1층 D블록16열 3',
 '2층 D블록2열 10',
 '3층 BOX7 1',
 '1층 A블록20열 4',
 '2층 C블록6열 10',
 '3층 C블록5열 7',
 '2층 B블록3열 2',
 '2층 A블록2열 3',
 '2층 D블록2열 2',
 '1층 D블록6열 6',
 '3층 N블록2열 13',
 '1층 E블록10열 5',
 '3층 M블록1열 15',
 '1층 B블록7열 8',
 '2층 D블록7열 3',
 '3층 N블록2열 14',
 '합창석 F블록2열 19',
 '2층 B블록7열 13',
 '1층 C블록12열 5',
 '합창석 H블록2열 9',
 '2층 BOX3 9',
 '3층 N블록1열 9',
 '2층 C블록3열 7',
 '합창석 G블록3열 33',
 '3층 M블록1열 8',
 '1층 B블록16열 8',
 '1층 A블록13열 5',
 '1층 D블록20열 3',
 '1층 B블록11열 2',
 '3층 C블록7열 11',
 '3층 M블록2열 10',
 '2층 A블록3열 3',
 '2층 E블록1열 13',
 '합창석 F블록2열 2',
 '1층 D블록11열 2',
 '2층 E블록3열 4',
 '3층 G블록5열 2',
 '1층 C블록6열 9',
 '1층 A블록3열 6',
 '합창석 H블록2열 7',
 '3층 D블록5열 8',
 '2층 A블록7열 1',
 '2층 E블록5열 15',
 '3층 E블록7열 13',
 '2층 C블록3열 1',
 '3층 G블록5열 3',
 '1층 E블록5열 4',
 '1층 C블록17열 6',
 '2층 E블록8열 3',
 '합창석 G블록1열 12',
 '2층 A블록3열 14',
 '2층 E블록5열 13',
 '1층 B블록5열 5',
 '2층 A블록5열 16',
 '2층 C블록1열 7',
 '3층 E블록4열 1',
 '3층 E블록5열 10',
 '1층 B블록19열 13',
 '1층 B블록16열 1',
 '1층 C블록20열 11',
 '1층 E블록1열 9',
 '1층 E블록15열 3',
 '합창석 F블록3열 7',
 '1층 C블록6열 2',
 '2층 A블록1열 8',
 '합창석 G블록4열 32',
 '2층 BOX2 3',
 '1층 E블록5열 3',
 '1층 C블록9열 4',
 '1층 E블록6열 3',
 '1층 B블록22열 4',
 '3층 G블록6열 2',
 '1층 D블록7열 6',
 '2층 A블록6열 14',
 '1층 D블록8열 8',
 '3층 D블록6열 12',
 '3층 BOX11 1',
 '3층 BOX8 1',
 '1층 E블록6열 6',
 '1층 C블록9열 3',
 '1층 C블록19열 13',
 '1층 A블록19열 9',
 '2층 C블록2열 11',
 '1층 E블록4열 7',
 '1층 D블록18열 12',
 '3층 D블록7열 5',
 '2층 BOX5 4',
 '1층 A블록5열 3',
 '1층 B블록14열 3',
 '1층 D블록14열 12',
 '1층 D블록12열 9',
 '3층 BOX7 4',
 '3층 B블록4열 4',
 '1층 B블록19열 7',
 '1층 C블록13열 8',
 '1층 C블록18열 12',
 '1층 B블록21열 6',
 '1층 D블록14열 7',
 '1층 A블록8열 4',
 '1층 A블록17열 7',
 '1층 A블록2열 2',
 '2층 D블록6열 4',
 '2층 B블록7열 2',
 '2층 B블록1열 5',
 '1층 C블록5열 9',
 '2층 C블록6열 4',
 '3층 E블록4열 7',
 '1층 D블록12열 4',
 '1층 B블록6열 7',
 '2층 A블록1열 4',
 '1층 C블록15열 12',
 '3층 B블록7열 9',
 '2층 A블록4열 1',
 '3층 D블록4열 6',
 '1층 C블록2열 7',
 '3층 BOX8 9',
 '3층 B블록5열 7',
 '1층 D블록13열 10',
 '3층 G블록4열 5',
 '3층 D블록7열 9',
 '2층 BOX2 4',
 '2층 B블록3열 3',
 '1층 B블록21열 2',
 '1층 C블록16열 7',
 '2층 A블록6열 1',
 '1층 C블록8열 1',
 '1층 D블록13열 2',
 '2층 E블록2열 14',
 '1층 E블록11열 5',
 '1층 B블록21열 7',
 '1층 C블록1열 7',
 '1층 B블록2열 10',
 '1층 C블록21열 12',
 '3층 E블록5열 7',
 '3층 G블록3열 3',
 '합창석 F블록1열 11',
 '3층 D블록4열 4',
 '1층 D블록8열 9',
 '1층 E블록19열 7',
 '합창석 H블록1열 3',
 '3층 C블록4열 1',
 '1층 C블록13열 9',
 '2층 D블록7열 11',
 '1층 D블록13열 7',
 '1층 D블록2열 8',
 '1층 B블록18열 1',
 '1층 C블록20열 3',
 '3층 N블록2열 2',
 '2층 C블록1열 9',
 '1층 E블록2열 2',
 '1층 B블록15열 3',
 '3층 G블록7열 4',
 '2층 C블록4열 4',
 '1층 B블록9열 3',
 '1층 D블록19열 7',
 '2층 A블록6열 5',
 '2층 B블록5열 4',
 '2층 B블록3열 7',
 '합창석 G블록1열 8',
 '1층 E블록18열 1',
 '1층 E블록17열 3',
 '3층 M블록2열 5',
 '3층 G블록5열 7',
 '3층 BOX8 5',
 '1층 B블록13열 2',
 '2층 A블록3열 5',
 '1층 A블록18열 9',
 '1층 B블록22열 11',
 '2층 A블록1열 3',
 '2층 C블록5열 9',
 '2층 BOX4 5',
 '2층 C블록7열 5',
 '2층 A블록2열 6',
 '1층 B블록1열 3',
 '1층 C블록10열 2',
 '3층 F블록7열 3',
 '2층 B블록1열 2',
 ...]

In [6]:
df=df.drop('membership_type_6', axis=1)

In [59]:
df[df.duplicated(keep=False)].sort_values(by='performance_code')

,age,gender,membership_type_1,membership_type_2,membership_type_3,membership_type_4,membership_type_5,tran_date,tran_time,play_date,play_st_time,seat,price,ticket_cancel,discount_type,performance_code,pre_open_date,open_date,genre,place,running_time,intermission,member_yn,floor,block,seat_line,seat_number
189486,30.0,M,무료,NaN,NaN,NaN,NaN,20200103,28,20200329,1700,합창석 G블록4열 14,50000,2,일반,1141,20191229.0,20191230.0,독주,콘서트홀,120,15,Y,합창석,G블록,4열,14
373565,30.0,M,무료,NaN,NaN,NaN,NaN,20200103,28,20200329,1700,합창석 G블록4열 14,50000,2,일반,1141,20191229.0,20191230.0,독주,콘서트홀,120,15,Y,합창석,G블록,4열,14
492382,30.0,M,무료,NaN,NaN,NaN,NaN,20200103,28,20200329,1700,합창석 H블록3열 9,35000,2,조기예매 할인30%,1141,20191229.0,20191230.0,독주,콘서트홀,120,15,Y,합창석,H블록,3열,9
627490,30.0,M,무료,NaN,NaN,NaN,NaN,20200103,28,20200329,1700,합창석 H블록3열 9,35000,2,조기예매 할인30%,1141,20191229.0,20191230.0,독주,콘서트홀,120,15,Y,합창석,H블록,3열,9
1625092,30.0,M,무료,NaN,NaN,NaN,NaN,20200103,28,20200329,1700,합창석 G블록4열 15,50000,2,일반,1141,20191229.0,20191230.0,독주,콘서트홀,120,15,Y,,,,0
1910975,30.0,M,무료,NaN,NaN,NaN,NaN,20200103,28,20200329,1700,합창석 G블록4열 15,50000,2,일반,1141,20191229.0,20191230.0,독주,콘서트홀,120,15,Y,,,,0
1079757,50.0,F,무료,NaN,NaN,NaN,NaN,20190624,36,20191119,2000,1층 C블록6열 6,200000,2,일반,1556,20190608.0,20190610.0,실내악,콘서트홀,120,15,Y,,,,0
1899747,50.0,F,무료,NaN,NaN,NaN,NaN,20190624,36,20191119,2000,1층 C블록6열 6,200000,2,일반,1556,20190608.0,20190610.0,실내악,콘서트홀,120,15,Y,,,,0
41923,50.0,F,골드,무료,그린,NaN,NaN,20191201,1510,20200605,2000,2층 E블록1열 11,37000,2,공연예매권,1700,20191129.0,20191130.0,교향곡,콘서트홀,120,15,Y,2층,E블록,1열,11
719290,50.0,F,골드,무료,그린,NaN,NaN,20191201,1510,20200605,2000,2층 E블록1열 11,37000,2,공연예매권,1700,20191129.0,20191130.0,교향곡,콘서트홀,120,15,Y,2층,E블록,1열,11
333945,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20230517,1505,20230608,1930,2층 D블록4열 11,45000,2,문화릴레이(1인2매/공연유료티켓제시)10%,2824,20230505.0,20230507.0,교향곡,콘서트홀,120,15,N,2층,D블록,4열,11
506440,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20230517,1505,20230608,1930,2층 D블록4열 11,45000,2,문화릴레이(1인2매/공연유료티켓제시)10%,2824,20230505.0,20230507.0,교향곡,콘서트홀,120,15,N,2층,D블록,4열,11
3435,60.0,F,블루,무료,NaN,NaN,NaN,20230610,133,20230624,1700,2층 A블록3열 18,20000,2,장애인/국가유공자 할인50%,2830,20230505.0,20230507.0,교향곡,콘서트홀,120,15,Y,2층,A블록,3열,18
763897,60.0,F,블루,무료,NaN,NaN,NaN,20230610,133,20230624,1700,2층 A블록3열 18,20000,2,장애인/국가유공자 할인50%,2830,20230505.0,20230507.0,교향곡,콘서트홀,120,15,Y,2층,A블록,3열,18

In [75]:
df[df['discount_type'].str.contains('예매')]

,age,gender,membership_type_1,membership_type_2,membership_type_3,membership_type_4,membership_type_5,tran_date,tran_time,play_date,play_st_time,seat,price,ticket_cancel,discount_type,performance_code,pre_open_date,open_date,genre,place,running_time,intermission,member_yn,floor,block,seat_line,seat_number
61,60.0,M,골드,무료,NaN,NaN,NaN,20181110,1610,20181208,1700,1층 C블록6열 7,60000,0,조기예매 할인40%,1242,NaN,20181029.0,클래식,콘서트홀,140,20,Y,1층,C블록,6열,7
99,30.0,F,블루,무료,NaN,NaN,NaN,20191217,1147,20200528,2000,1층 C블록19열 8,35000,2,공연예매권,317,NaN,20200516.0,교향곡,콘서트홀,120,15,Y,1층,C블록,19열,8
145,30.0,M,무료,NaN,NaN,NaN,NaN,20220308,2339,20220406,1930,1층 D블록6열 1,84000,0,조기예매 할인(1인8매/3월11일까지)30%,1997,20220306.0,20220307.0,클래식,콘서트홀,120,15,Y,1층,D블록,6열,1
222,20.0,F,무료,싹틔우미,NaN,NaN,NaN,20190526,1353,20190825,1700,합창석 G블록3열 9,36000,0,조기예매 할인10%,2086,NaN,20190519.0,클래식,콘서트홀,100,15,Y,합창석,G블록,3열,9
255,10.0,M,블루,무료,싹틔우미,NaN,NaN,20221103,741,20221118,1930,1층 B블록1열 5,105000,2,조기예매 할인(1인2매/~10월31일까지)30%,1466,20221021.0,20221021.0,교향곡,콘서트홀,120,15,Y,1층,B블록,1열,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1920117,40.0,F,무료,NaN,NaN,NaN,NaN,20221128,1601,20230106,1930,1층 A블록13열 11,63000,2,조기예매할인(1인8매/~12.2까지)30%,801,NaN,20221209.0,클래식,콘서트홀,120,0,Y,,,,0
1920181,50.0,F,블루,무료,NaN,NaN,NaN,20230225,1502,20230523,1930,1층 C블록1열 2,77000,2,조기예매 할인(1인8매/~3월3일까지)30%,221,20230225.0,20230226.0,클래식,콘서트홀,150,15,Y,,,,0
1920361,40.0,F,무료,NaN,NaN,NaN,NaN,20220825,106,20221103,1930,3층 D블록6열 3,35000,0,조기예매할인(1인2매/~9월8일까지)30%,874,20220822.0,20220822.0,교향곡,콘서트홀,120,15,Y,,,,0
1920469,50.0,F,골드,무료,NaN,NaN,NaN,20220828,1008,20220925,1700,3층 N블록2열 1,42000,0,조기예매 할인(1인8매/~8월31일까지)30%,1693,20220724.0,20220725.0,클래식,콘서트홀,120,15,Y,,,,0
1920743,40.0,F,무료,NaN,NaN,NaN,NaN,20191221,1528,20200105,1700,3층 N블록1열 10,47000,0,조기예매 할인5%,1240,NaN,20190727.0,클래식,콘서트홀,100,15,Y,,,,0

In [65]:
df[(df['discount_type']=='차액')]

,age,gender,membership_type_1,membership_type_2,membership_type_3,membership_type_4,membership_type_5,tran_date,tran_time,play_date,play_st_time,seat,price,ticket_cancel,discount_type,performance_code,pre_open_date,open_date,genre,place,running_time,intermission,member_yn,floor,block,seat_line,seat_number
899,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20200626,1916,20200630,2000,2층 A블록8열 3,3000,0,차액,1418,20200531.0,20200531.0,독주,콘서트홀,100,15,N,2층,A블록,8열,3
1912,50.0,F,블루,골드,무료,NaN,NaN,20230131,1638,20230204,1700,2층 E블록8열 3,12000,0,차액,312,NaN,20230120.0,교향곡,콘서트홀,120,0,Y,2층,E블록,8열,3
2455,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20230325,1924,20230329,1930,2층 E블록8열 7,40000,0,차액,2745,NaN,20230210.0,교향곡,콘서트홀,110,15,N,2층,E블록,8열,7
2608,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20211022,1907,20211026,1930,2층 E블록8열 1,5000,0,차액,912,20210911.0,20210912.0,클래식,콘서트홀,110,20,N,2층,E블록,8열,1
2655,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20220710,1852,20220714,1930,합창석 G블록1열 11,40000,0,차액,2636,20220527.0,20220528.0,콘서트,콘서트홀,120,15,N,합창석,G블록,1열,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1916956,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20190722,1945,20190726,2000,합창석 G블록1열 1,5000,0,차액,2503,20190601.0,20190602.0,교향곡,콘서트홀,120,15,N,,,,0
1917211,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20221029,1931,20221102,2000,합창석 G블록1열 12,5000,0,차액,2756,20220805.0,20220806.0,교향곡,콘서트홀,101,20,N,,,,0
1919062,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20230221,1659,20230225,1700,1층 C블록22열 3,65000,2,차액,834,20221118.0,20221119.0,독주,콘서트홀,120,20,N,,,,0
1919889,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20220815,1918,20220819,1930,합창석 G블록1열 19,8000,0,차액,545,20220701.0,20220702.0,합창,콘서트홀,90,0,N,,,,0
1920678,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20211130,1632,20211204,1700,2층 E블록8열 1,10000,0,차액,121,20210910.0,20210910.0,교향곡,콘서트홀,120,15,N,,,,0

### 멤버십 정리

In [70]:
member=df.iloc[:,2:7]

In [71]:
merged_column = member.fillna('').astype(str).apply(' '.join, axis=1)

In [78]:
df=df.drop(columns=['membership_type_1', 'membership_type_2', 'membership_type_3', 'membership_type_4', 'membership_type_5'])

In [95]:
df['무료']=0
df['골드']=0
df['블루']=0
df['그린']=0
df['노블']=0
df['싹틔우미']=0

In [96]:
for index in df.index:
    if merged_column[index].count('무료')==1:
        df.loc[index, '무료']=1
    if merged_column[index].count('골드')==1:
        df.loc[index, '골드']=1
    if merged_column[index].count('블루')==1:
        df.loc[index, '블루']=1
    if merged_column[index].count('그린')==1:
        df.loc[index, '그린']=1
    if merged_column[index].count('노블')==1:
        df.loc[index, '노블']=1
    if merged_column[index].count('싹틔우미')==1:
        df.loc[index, '싹틔우미']=1

### 진짜 취소한 고객 탐색

In [107]:
df[df['ticket_cancel']==2]

,age,gender,tran_date,tran_time,play_date,play_st_time,seat,price,ticket_cancel,discount_type,performance_code,pre_open_date,open_date,genre,place,running_time,intermission,member_yn,무료,골드,그린,블루,싹틔우미,노블
0,50.0,F,20220114,1512,20220204,2000,3층 BOX9 10,10000,2,일반,302,20220114.0,20220115.0,교향곡,콘서트홀,120,15,Y,1,1,1,0,0,0
5,30.0,F,20181124,1145,20190323,2000,1층 A블록2열 1,144000,2,블루회원 할인20%,528,20181119.0,20181119.0,교향곡,콘서트홀,100,15,Y,1,0,0,1,0,0
13,NaN,NaN,20220624,1618,20220629,1930,3층 BOX12 3,20000,2,일반,2344,20220430.0,20220430.0,교향곡,콘서트홀,110,15,N,0,0,0,0,0,0
15,50.0,M,20221030,1645,20221227,2000,2층 D블록8열 3,120000,2,일반,2631,20221105.0,20221030.0,교향곡,콘서트홀,120,20,Y,1,1,0,0,0,0
33,50.0,M,20230514,1606,20230629,1930,3층 M블록1열 2,10000,2,일반,2835,20230505.0,20230507.0,교향곡,콘서트홀,120,15,Y,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1920821,50.0,F,20181209,1407,20190224,1700,2층 E블록2열 1,38000,2,골드회원 할인30%,1400,20181209.0,20181210.0,성악,콘서트홀,120,20,Y,1,1,0,1,0,0
1920835,NaN,NaN,20181112,1009,20181220,2000,2층 D블록3열 11,0,2,초대권,419,NaN,20181110.0,콘서트,콘서트홀,100,20,N,0,0,0,0,0,0
1920836,50.0,M,20210917,1544,20211009,1700,2층 B블록3열 11,35000,2,골드회원 할인30%,957,20210917.0,20210918.0,교향곡,콘서트홀,120,15,Y,1,1,0,0,0,0
1920842,50.0,F,20220410,1401,20220626,1700,1층 C블록5열 9,142000,2,그린회원 할인5%,1789,20220410.0,20220411.0,독주,콘서트홀,95,20,Y,1,0,1,0,0,0
1920853,60.0,F,20210618,1509,20210704,1500,1층 A블록2열 2,90000,2,일반,887,20210618.0,20210620.0,교향곡,콘서트홀,110,20,Y,1,0,1,0,0,0

In [8]:
df.columns

Index(['age', 'gender', 'membership_type_1', 'membership_type_2',
       'membership_type_3', 'membership_type_4', 'membership_type_5',
       'membership_type_6', 'tran_date', 'tran_time', 'play_date',
       'play_st_time', 'seat', 'price', 'ticket_cancel', 'discount_type',
       'performance_code', 'pre_open_date', 'open_date', 'genre', 'place',
       'running_time', 'intermission', 'member_yn'],
      dtype='object')

In [52]:
indices=['discount_type','seat', 'tran_date', 'tran_time']

In [53]:
dup_df=df[df.loc[:,~df.columns.isin(indices)].duplicated(keep=False)]

In [60]:
df.columns

Index(['age', 'gender', 'membership_type_1', 'membership_type_2',
       'membership_type_3', 'membership_type_4', 'membership_type_5',
       'tran_date', 'tran_time', 'play_date', 'play_st_time', 'seat', 'price',
       'ticket_cancel', 'discount_type', 'performance_code', 'pre_open_date',
       'open_date', 'genre', 'place', 'running_time', 'intermission',
       'member_yn'],
      dtype='object')

In [59]:
dup_df.sort_values(by=list(df.columns))

,age,gender,membership_type_1,membership_type_2,membership_type_3,membership_type_4,membership_type_5,tran_date,tran_time,play_date,play_st_time,seat,price,ticket_cancel,discount_type,performance_code,pre_open_date,open_date,genre,place,running_time,intermission,member_yn
152718,10.0,F,골드,무료,싹틔우미,NaN,NaN,20190407,149,20190704,2000,1층 A블록15열 3,72000,2,골드회원 할인10%,990,20190406.0,20190407.0,클래식,콘서트홀,100,15,Y
441650,10.0,F,골드,무료,싹틔우미,NaN,NaN,20190529,0,20190925,2000,3층 G블록5열 11,57000,2,골드회원 할인5%,942,NaN,20190527.0,클래식,콘서트홀,80,0,Y
1812799,10.0,F,골드,무료,싹틔우미,NaN,NaN,20190529,6,20190925,2000,1층 D블록18열 2,114000,2,골드회원 할인5%,942,NaN,20190527.0,클래식,콘서트홀,80,0,Y
612402,10.0,F,골드,무료,싹틔우미,NaN,NaN,20190529,8,20190925,2000,1층 D블록19열 13,114000,2,골드회원 할인5%,942,NaN,20190527.0,클래식,콘서트홀,80,0,Y
1080760,10.0,F,골드,무료,싹틔우미,NaN,NaN,20190531,221,20190925,2000,3층 A블록1열 2,57000,2,골드회원 할인5%,942,NaN,20190527.0,클래식,콘서트홀,80,0,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20230702,1157,20230706,1100,1층 D블록6열 10,30000,0,일반,2819,20230428.0,20230429.0,NaN,콘서트홀,120,15,N
239885,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20230703,1015,20230707,1930,1층 A블록8열 10,50000,0,"국가유공자,의상자1~2급(동반1인)50%",914,20230409.0,20230410.0,독주,콘서트홀,100,20,N
172883,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20230703,1407,20230707,1930,합창석 G블록2열 30,50000,0,일반,914,20230409.0,20230410.0,독주,콘서트홀,100,20,N
1824585,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20230703,1905,20230707,1930,합창석 F블록1열 2,50000,0,일반,914,20230409.0,20230410.0,독주,콘서트홀,100,20,N
1831784,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20230703,1920,20230707,1930,합창석 G블록2열 28,50000,0,일반,914,20230409.0,20230410.0,독주,콘서트홀,100,20,N

### 좌석번호 분리

In [17]:
df['floor']=''
df['block']=''
df['seat_line']=''
df['seat_number']=0

In [18]:
for index, row in df.iterrows():
    df.loc[index,'floor']=row['seat'].split()[0]
    if row['seat'].split()[1][:3]=='BOX':
        df.loc[index,'block']=row['seat'].split()[1][:4]
    else:
        df.loc[index,'block']=row['seat'].split()[1][:3]
        df.loc[index,'seat_line']=row['seat'].split()[1][3:]
    df.loc[index,'seat_number']=int(row['seat'].split()[2])

KeyboardInterrupt:

In [ ]:
row['seat'].split()[1][:4]

In [ ]:
df['seat_number']

In [47]:
df

,age,gender,membership_type_1,membership_type_2,membership_type_3,membership_type_4,membership_type_5,tran_date,tran_time,play_date,...,open_date,genre,place,running_time,intermission,member_yn,floor,block,seat_line,seat_number
0,50.0,F,골드,무료,그린,NaN,NaN,20220114,1512,20220204,...,20220115.0,교향곡,콘서트홀,120,15,Y,3층,BOX9,,10
4,50.0,M,무료,NaN,NaN,NaN,NaN,20220206,1615,20220302,...,20220110.0,독주,콘서트홀,90,0,Y,1층,B블록,12열,7
5,30.0,F,블루,무료,NaN,NaN,NaN,20181124,1145,20190323,...,20181119.0,교향곡,콘서트홀,100,15,Y,1층,A블록,2열,1
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20191020,1459,20191109,...,20191023.0,교향곡,콘서트홀,100,15,N,3층,E블록,4열,8
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20190613,954,20190723,...,20190602.0,교향곡,콘서트홀,120,20,N,2층,D블록,8열,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1920853,60.0,F,무료,그린,NaN,NaN,NaN,20210618,1509,20210704,...,20210620.0,교향곡,콘서트홀,110,20,Y,,,,0
1920855,50.0,M,무료,NaN,NaN,NaN,NaN,20230522,1729,20230613,...,20230507.0,교향곡,콘서트홀,120,15,Y,,,,0
1920856,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20201009,1652,20201020,...,20200920.0,클래식,콘서트홀,120,15,N,,,,0
1920858,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20200726,1655,20200818,...,20200720.0,합창,콘서트홀,110,15,N,,,,0
1920864,20.0,F,무료,싹틔우미,NaN,NaN,NaN,20221224,1223,20230408,...,20221223.0,교향곡,콘서트홀,120,0,Y,,,,0

In [46]:
df[(df['seat']=='1층 A블록15열 9')&(df['price']==0)]

array([ 283,  298,  287, 2839, 2198,  315, 2505,   80, 2818,  833,  588,
       2279, 2464, 2744,   96, 1537, 2330,  893, 2538, 1192,  448, 1829,
        305, 1355, 2825,  961, 2199,  232, 2749,  357, 1216,  250, 1416,
        538, 1248, 2822,  229, 2803,  530, 2508, 1993, 2558, 1420,  234,
        505,  326,  421, 2840, 1732, 2777,  130, 1293,  557, 2903,  289,
        875, 1861, 2429,  320,   76, 1716, 2936, 1864, 1533,  294,  311,
        536,   38,  148,    3, 2835,  410, 1659, 2761,  145, 1488,  310,
        906,  544,  898, 1242,  137, 2222, 1496, 2503, 2084,  197,  314,
        500, 2174, 1546,  498, 2215, 2674, 1005,  328,   95, 2615, 1283,
        333, 2548,   44,  166, 2751,  988, 2220, 1711,  836, 2498, 2534,
        455, 1863,  279,  827, 1684,  881,  284,  939, 2634,  236, 2775,
          1, 2365, 1421, 2817, 1712,  793,  312, 2439, 2261, 2480,  646,
       1263, 2841,   72,  974, 1285, 2563, 2831, 1354, 2472,  108,  457,
       1554, 1353,  211, 1400, 1178,  331, 2791, 1418, 1146, 1646, 1169,
        863, 2497,  803, 2627,  902,  715,  885, 1276, 1006, 2291, 1269,
        183, 2728,  299, 2164,  231, 1261,  179, 2609, 1231, 1206, 1211,
       2299, 1475, 2932, 2132, 2747,  233, 1209,  353, 1243, 1158, 2167,
        878,  915,  492, 2011, 1233,  366,  963,  512,  350, 2731, 1140,
        302,  504, 1339, 1215,   53,  897,  913, 2230, 2496, 2569, 1232,
        835, 1498, 2462, 1669, 2732, 2020, 1532, 2180,  295,  542, 1714,
        899,  522,  404, 1208, 2221, 2017, 2753,  503, 1159,  450, 1789,
        874, 2820, 1658,   77, 1534, 2710, 2730, 2597, 2745,   40, 2010,
       2157, 1521, 1286, 1160,  241,  313, 2893, 2624, 1003, 2838, 2829,
        191,  174, 1281, 2192, 2331,  303,  327, 2046, 2762, 2482,  936,
        238,  292,  441, 1307, 2619, 2531,  996, 2218, 2009, 2827,  308,
        461,  880, 1666,  352,  347,  532, 2833, 1476, 2776, 2297, 2065,
       1828, 2491,  427,  984,  253,  951,  171, 1182,  297,  918, 1157,
        123, 2085,  420, 2604,  282,  956,  801,  422,  397,  982,   79,
        910,  497, 1635, 2596, 1246, 1764, 1284,  332,  451,  447, 1244,
        938, 1277, 2509, 1203,  873, 2616,  543, 2161, 2598, 2617, 2059,
       2642, 1429, 2158,  460,  163, 1717,  442, 1424,  363,   43,  528,
       2231,  348, 1725,  541,   42, 1633, 1328, 1464,  839, 2481, 2836,
        725,  919,  876,  860,   60,  933, 1419,  937,  120,  453, 2630,
        258, 1412, 2271,  300,  547, 1509, 2536,  551, 1485, 1718,  296,
       2489,  521,  319,  957,  266, 1487, 2830, 2837, 2175, 2181, 2512,
        900, 2268, 1565,  215,  545, 1161, 2796, 2304, 1693,  306,  162,
        322,  390, 2332,  267, 1467,   68,  169, 2824,  277,  167, 2577,
        291,  518, 2290, 1417, 2131,  849, 1388,  857,  210,  212, 1316,
        834,  230,  285,  165,  403, 1997, 2504,  903, 2253, 1734,  458,
       2828,  318,  989,  293,  142,   30, 2937,  323, 1199, 1862,  914,
        172,  221,   31, 1700, 1011, 2556, 1218, 1508, 1292,  276, 2034,
        912,  556, 2778,  324, 1520,  452,  888, 1483,  456, 2369, 1671,
       1869,  949, 2087,  531,  383,  555, 1715, 2169, 2344, 2834, 1503,
        309,  121,  188,  217, 1010, 1150,  831,  942,  449, 2007, 1708,
       2134,  852, 2832,  502,  501, 1653,  436, 1342, 1282,  349, 2488,
       1205, 2187, 2570, 1466,   23,  147,  905,  219,  321,  227, 2595,
       1710,  802,  105,  552, 2821,  104,  248,  122, 1210, 2636,  354,
       1358,  850, 2748,  438, 1351,  317,  131,  496, 2823,  959,  550,
         81, 2040,  579,  981,  533, 2252,  325,  275,  290, 2826, 2298,
       1260,   71,  164,  960, 2807,  985,  546,  800,  499,  828, 2487,
         29,   39, 2088, 1200, 1176,  648,  896, 2333,  170, 2463, 2816,
       1763, 1415,  168, 2746,   61, 2938, 2490, 1002, 1234, 2136, 1645,
       2485, 2484, 2733,  173, 1676,  385, 2191, 1866, 1141, 2819, 2262,
        887,  879, 2641, 1713, 2727,  124,  794, 1528, 1735, 1685, 1382,
       2935,  877, 1470, 2565,  582, 2478,  495,  916,  419, 2260,  580,
       2493, 1834,  214, 2194,  815,  281,  161,  245, 2168, 1221, 2177,
        647,  948, 1865, 1497, 2486,  494,  534, 1692, 1472, 1556, 2640,
         54, 2631,  351, 2171, 1438, 2495, 2086,    7,  537, 1004, 2734,
        186,  895,   94, 2217,  213, 2756,  837,  307,  405,  743, 1315,
       2137,  560,  280, 1833,  454,  119, 1207,  304, 1241,  160, 1499,
       2008,  459,  446,  144,  301, 1535, 1618,   78, 2492], dtype=int64)

In [31]:
df['seat']

0            3층 BOX9 10
4           1층 B블록12열 7
5            1층 A블록2열 1
6            3층 E블록4열 8
7            2층 D블록8열 4
               ...
1920853      1층 A블록2열 2
1920855      3층 A블록6열 4
1920856    1층 D블록16열 12
1920858     1층 D블록20열 8
1920864      3층 B블록5열 4
Name: seat, Length: 1096968, dtype: object

### 정가 찾기 - 같은 공연, 같은 자리 이용

In [436]:
for index, row in df.iloc[:100,].iterrows():
    if row['discount_type']=='일반':
        df.loc[index, 'original_price']=df.loc[index, 'price']
    else:
        if row['seat'][:3]=='합창석':
            df.loc[index, 'original_price']=df[(df['performance_code']==row['performance_code'])&(df['discount_type']=='일반')
                                 &(df['seat'].str[:9]==row['seat'][:9])]['price'].mean()
        elif row['seat'][3:6]=='BOX':
            df.loc[index, 'original_price']=df[(df['performance_code']==row['performance_code'])&(df['discount_type']=='일반')
                                 &(df['seat'].str[:8]==row['seat'][:8])]['price'].mean()
        else:
            df.loc[index, 'original_price']=df[(df['performance_code']==row['performance_code'])&(df['discount_type']=='일반')
                                 &(df['seat'].str[:9]==row['seat'][:9])]['price'].mean()

In [482]:
df[(df['performance_code']==row['performance_code'])
                                 &(df['seat'].str[:9]==row['seat'][:9])].iloc[0,]

age                        30.0
gender                        F
membership_type_1            블루
membership_type_2            무료
membership_type_3           NaN
membership_type_4           NaN
membership_type_5           NaN
membership_type_6           NaN
tran_date              20181124
tran_time                  1145
play_date              20190323
play_st_time               2000
seat                 1층 A블록2열 1
price                    144000
ticket_cancel                 2
discount_type        블루회원 할인20%
performance_code            528
pre_open_date        20181119.0
open_date            20181119.0
genre                       교향곡
place                      콘서트홀
running_time                100
intermission                 15
member_yn                     Y
original_price         260000.0
Name: 5, dtype: object

In [455]:
df.loc[index, 'original_price']

120000.0

In [458]:
df[df['original_price']!=0].iloc[2,]

age                        30.0
gender                        F
membership_type_1            블루
membership_type_2            무료
membership_type_3           NaN
membership_type_4           NaN
membership_type_5           NaN
membership_type_6           NaN
tran_date              20181124
tran_time                  1145
play_date              20190323
play_st_time               2000
seat                 1층 A블록2열 1
price                    144000
ticket_cancel                 2
discount_type        블루회원 할인20%
performance_code            528
pre_open_date        20181119.0
open_date            20181119.0
genre                       교향곡
place                      콘서트홀
running_time                100
intermission                 15
member_yn                     Y
original_price         260000.0
Name: 5, dtype: object

### 정가 찾기 - 할인율, 최종 결제 가격 이용

In [307]:
'''
def extract_percentage(value):
    match = re.search(r'(\d+)%', value)
    if match:
        return int(match.group(1))
    return None
'''

"\ndef extract_percentage(value):\n    match = re.search(r'(\\d+)%', value)\n    if match:\n        return int(match.group(1))\n    return None\n"

In [ ]:
df['discount_percent']=df['discount_type'].apply(extract_percentage)
df['discount_percent'] = df['discount_percent'].fillna(0).astype(int)
df['original_price']=df['price']/(100-df['discount_percent'])*100
df[df['discount_percent'].isna()==False]['discount_percent'].astype(int)
df['original_price']=np.ceil(df['original_price'] / 1000) * 1000
df['original_price']=df['original_price'].astype(int)

### 정가 찾기 - 둘다 이용

In [723]:
df['discount_percent']=df['discount_type'].apply(extract_percentage)
df['original_price']=df['price']/(100-df['discount_percent'])*100
df[df['discount_percent'].isna()==False]['discount_percent'].astype(int)
df['original_price']=np.ceil(df['original_price'] / 1000) * 1000
df.loc[df['discount_type']=='일반','original_price']=df[df['discount_type']=='일반']['price']

In [724]:
nan_indices = df[(df['original_price'].isna())|(df['original_price']==0)].index

In [725]:
df_non=df[df['original_price']>0]

In [ ]:
for index in nan_indices:
    condition = (df_non['performance_code'] == df.loc[index, 'performance_code']) & \
                (df_non['floor'] == df.loc[index, 'floor']) & \
                (df_non['block'] == df.loc[index, 'block']) & \
                (df_non['seat_line'] == df.loc[index, 'seat_line'])
    
    rows = df_non[condition][['seat_number', 'original_price']]
    rows['key'] = rows['seat_number'] - df.loc[index, 'seat_number']
    
    if not rows['key'].empty:
        min_key_value = rows['key'].min()
        min_price = rows[rows['key'] == min_key_value]['original_price'].mode().values[0]
        df.at[index, 'original_price'] = min_price

In [ ]:
df[df['original_price'].isna()]

In [662]:
df.loc[:347,]['original_price'].value_counts().reset_index()

    original_price  count
0          40000.0     10
1          30000.0     10
2          10000.0      8
3          90000.0      7
4          50000.0      7
5          20000.0      7
6         120000.0      6
7         110000.0      6
8          70000.0      6
9         150000.0      6
10        130000.0      3
11        180000.0      3
12        100000.0      3
13         60000.0      1
14         75000.0      1
15        300000.0      1
16         77000.0      1
17         55000.0      1
18         65000.0      1
19        210000.0      1

In [16]:
df.groupby('performance_code')

In [606]:
df[(df['performance_code']==827)&(df['floor']=='2층')&(df['block']=='D블록')&(df['seat_line']=='7열')]

,age,gender,membership_type_1,membership_type_2,membership_type_3,membership_type_4,membership_type_5,membership_type_6,tran_date,tran_time,...,place,running_time,intermission,member_yn,original_price,discount_percent,flour,block,seat_line,seat_number
166474,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20190613,954,...,콘서트홀,120,20,N,0,0,2층,D블록,7열,3
483923,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20190613,954,...,콘서트홀,120,20,N,0,0,2층,D블록,7열,9
503664,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20190613,954,...,콘서트홀,120,20,N,0,0,2층,D블록,7열,10
537003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20190613,954,...,콘서트홀,120,20,N,0,0,2층,D블록,7열,13
638904,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20190613,954,...,콘서트홀,120,20,N,0,0,2층,D블록,7열,8
827426,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20190613,954,...,콘서트홀,120,20,N,0,0,2층,D블록,7열,14
872710,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20190613,954,...,콘서트홀,120,20,N,0,0,2층,D블록,7열,1
875418,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20190613,954,...,콘서트홀,120,20,N,0,0,2층,D블록,7열,6
882770,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20190613,954,...,콘서트홀,120,20,N,0,0,2층,D블록,7열,5
940699,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20190613,954,...,콘서트홀,120,20,N,0,0,2층,D블록,7열,2
1543484,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20190613,954,...,콘서트홀,120,20,N,0,0,2층,D블록,7열,7
1695950,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20190613,954,...,콘서트홀,120,20,N,0,0,2층,D블록,7열,12
1795439,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20190613,954,...,콘서트홀,120,20,N,0,0,2층,D블록,7열,11
1850718,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20190613,954,...,콘서트홀,120,20,N,0,0,2층,D블록,7열,4

In [597]:
df.loc[1850718,]

age                         NaN
gender                      NaN
membership_type_1           NaN
membership_type_2           NaN
membership_type_3           NaN
membership_type_4           NaN
membership_type_5           NaN
membership_type_6           NaN
tran_date              20190613
tran_time                   954
play_date              20190723
play_st_time               2000
seat                 2층 D블록7열 4
price                         0
ticket_cancel                 0
discount_type               초대권
performance_code            827
pre_open_date        20190602.0
open_date            20190602.0
genre                       교향곡
place                      콘서트홀
running_time                120
intermission                 20
member_yn                     N
original_price                0
discount_percent              0
flour                        2층
block                       D블록
seat_line                    7열
seat_number                   4
Name: 1850718, dtype: object

In [509]:
df[df['seat'].str[3:6]=='BOX']['seat'].str[8:].str.strip().unique()

array(['10', '열 7', '1', '8', '4', '열 3', '5', '3', '2', '16', '열 4',
       '열 8', '7', '열 9', '열 6', '열 1', '11', '6', '13', '열 11', '열 5',
       '열 24', '열 10', '열 2', '14', '열 12', '9', '18', '12', '열 13', '15',
       '19', '열 14', '열 37', '열 16', '열 21', '열 15', '열 19', '17', '열 25',
       '열 33', '열 31', '열 28', '열 20', '열 32', '열 17', '열 30', '열 18',
       '열 23', '20', '열 29', '열 27', '열 22', '열 36', '열 26', '열 34',
       '열 35'], dtype=object)

In [485]:
df

,age,gender,membership_type_1,membership_type_2,membership_type_3,membership_type_4,membership_type_5,membership_type_6,tran_date,tran_time,...,performance_code,pre_open_date,open_date,genre,place,running_time,intermission,member_yn,original_price,discount_percent
0,50.0,F,골드,무료,그린,NaN,NaN,NaN,20220114,1512,...,302,20220114.0,20220115.0,교향곡,콘서트홀,120,15,Y,10000,0
4,50.0,M,무료,NaN,NaN,NaN,NaN,NaN,20220206,1615,...,897,20220109.0,20220110.0,독주,콘서트홀,90,0,Y,180000,0
5,30.0,F,블루,무료,NaN,NaN,NaN,NaN,20181124,1145,...,528,20181119.0,20181119.0,교향곡,콘서트홀,100,15,Y,180000,20
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20191020,1459,...,44,NaN,20191023.0,교향곡,콘서트홀,100,15,N,0,0
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20190613,954,...,827,20190602.0,20190602.0,교향곡,콘서트홀,120,20,N,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1920853,60.0,F,무료,그린,NaN,NaN,NaN,NaN,20210618,1509,...,887,20210618.0,20210620.0,교향곡,콘서트홀,110,20,Y,90000,0
1920855,50.0,M,무료,NaN,NaN,NaN,NaN,NaN,20230522,1729,...,2825,20230505.0,20230507.0,교향곡,콘서트홀,120,15,Y,10000,0
1920856,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20201009,1652,...,77,NaN,20200920.0,클래식,콘서트홀,120,15,N,0,0
1920858,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20200726,1655,...,850,20200719.0,20200720.0,합창,콘서트홀,110,15,N,0,0
1920864,20.0,F,무료,싹틔우미,NaN,NaN,NaN,NaN,20221224,1223,...,313,NaN,20221223.0,교향곡,콘서트홀,120,0,Y,30000,30

In [5]:
import pandas as pd

data = {'A': [1, 2, 3],
        'B': [4, 5, 6]}

df = pd.DataFrame(data)

# 확인하려는 행
row_to_check = pd.Series([1, 4], index=['A', 'B'])

# 특정 행이 데이터프레임에 포함되는지 여부 확인
is_contained = (df == row_to_check).all(axis=1).sum()
is_contained

1

In [73]:
df_con=df[df.iloc[:,20]=='콘서트홀']

In [43]:
df_con.iloc[:,19].value_counts().reset_index()

    genre   count
0     교향곡  522271
1     클래식  236966
2      합창  112297
3      독주   63503
4      성악   40385
5     실내악   34129
6     콘서트   23918
7     오페라   21707
8    복합장르    8705
9      기타    5843
10     재즈    1080
11  크로스오버     967
12    가족극     124

In [47]:
symphony=df_con[df_con.iloc[:,19]=='교향곡']

In [65]:
symphony[symphony.iloc[:,13]==10000].iloc[:,3].value_counts().reset_index()

  membership_type_2  count
0                무료  10606
1              싹틔우미   5344
2                그린   4375
3                골드   3495
4                노블    766