In [2]:
import pandas as pd
import numpy as np

data = pd.read_csv("bigcontest.csv")
df= data.copy() #원본 둔 채 copydata 생성

In [3]:
cthall = df[ df['place'] == '콘서트홀' ]
cthall # concerthall 에서 한 공연만 가지고 dataframe 생성

,age,gender,membership_type_1,membership_type_2,membership_type_3,membership_type_4,membership_type_5,membership_type_6,tran_date,tran_time,...,ticket_cancel,discount_type,performance_code,pre_open_date,open_date,genre,place,running_time,intermission,member_yn
0,50.0,F,골드,무료,그린,NaN,NaN,NaN,20220114,1512,...,2,일반,302,20220114.0,20220115.0,교향곡,콘서트홀,120,15,Y
4,50.0,M,무료,NaN,NaN,NaN,NaN,NaN,20220206,1615,...,0,일반,897,20220109.0,20220110.0,독주,콘서트홀,90,0,Y
5,30.0,F,블루,무료,NaN,NaN,NaN,NaN,20181124,1145,...,2,블루회원 할인20%,528,20181119.0,20181119.0,교향곡,콘서트홀,100,15,Y
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20191020,1459,...,0,초대권,44,NaN,20191023.0,교향곡,콘서트홀,100,15,N
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20190613,954,...,0,초대권,827,20190602.0,20190602.0,교향곡,콘서트홀,120,20,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1920853,60.0,F,무료,그린,NaN,NaN,NaN,NaN,20210618,1509,...,2,일반,887,20210618.0,20210620.0,교향곡,콘서트홀,110,20,Y
1920855,50.0,M,무료,NaN,NaN,NaN,NaN,NaN,20230522,1729,...,0,일반,2825,20230505.0,20230507.0,교향곡,콘서트홀,120,15,Y
1920856,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20201009,1652,...,0,초대권,77,NaN,20200920.0,클래식,콘서트홀,120,15,N
1920858,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20200726,1655,...,0,기획사판매,850,20200719.0,20200720.0,합창,콘서트홀,110,15,N
1920864,20.0,F,무료,싹틔우미,NaN,NaN,NaN,NaN,20221224,1223,...,0,청소년(만7세~만24세/본인만)30%,313,NaN,20221223.0,교향곡,콘서트홀,120,0,Y

In [4]:
cthall_unique = cthall[ (cthall['ticket_cancel']==2) | (cthall['price']==0) ]

In [5]:
cthall = cthall[cthall['ticket_cancel']==0]
cthall.shape

(864120, 24)

In [6]:
cthall

,age,gender,membership_type_1,membership_type_2,membership_type_3,membership_type_4,membership_type_5,membership_type_6,tran_date,tran_time,...,ticket_cancel,discount_type,performance_code,pre_open_date,open_date,genre,place,running_time,intermission,member_yn
4,50.0,M,무료,NaN,NaN,NaN,NaN,NaN,20220206,1615,...,0,일반,897,20220109.0,20220110.0,독주,콘서트홀,90,0,Y
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20191020,1459,...,0,초대권,44,NaN,20191023.0,교향곡,콘서트홀,100,15,N
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20190613,954,...,0,초대권,827,20190602.0,20190602.0,교향곡,콘서트홀,120,20,N
9,NaN,F,블루,무료,NaN,NaN,NaN,NaN,20190703,908,...,0,일반,1528,NaN,20190413.0,클래식,콘서트홀,100,15,N
11,50.0,F,무료,NaN,NaN,NaN,NaN,NaN,20191005,1417,...,0,K-lang 멤버십 회원(1인2매)20%,315,NaN,20191005.0,오페라,콘서트홀,120,15,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1920852,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20190503,1659,...,0,초대권,2253,20190519.0,20190519.0,클래식,콘서트홀,120,15,N
1920855,50.0,M,무료,NaN,NaN,NaN,NaN,NaN,20230522,1729,...,0,일반,2825,20230505.0,20230507.0,교향곡,콘서트홀,120,15,Y
1920856,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20201009,1652,...,0,초대권,77,NaN,20200920.0,클래식,콘서트홀,120,15,N
1920858,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20200726,1655,...,0,기획사판매,850,20200719.0,20200720.0,합창,콘서트홀,110,15,N
1920864,20.0,F,무료,싹틔우미,NaN,NaN,NaN,NaN,20221224,1223,...,0,청소년(만7세~만24세/본인만)30%,313,NaN,20221223.0,교향곡,콘서트홀,120,0,Y

In [7]:
cthall = cthall[ cthall['price'] !=0 ]
cthall.shape

(315158, 24)

In [8]:
cthall

,age,gender,membership_type_1,membership_type_2,membership_type_3,membership_type_4,membership_type_5,membership_type_6,tran_date,tran_time,...,ticket_cancel,discount_type,performance_code,pre_open_date,open_date,genre,place,running_time,intermission,member_yn
4,50.0,M,무료,NaN,NaN,NaN,NaN,NaN,20220206,1615,...,0,일반,897,20220109.0,20220110.0,독주,콘서트홀,90,0,Y
9,NaN,F,블루,무료,NaN,NaN,NaN,NaN,20190703,908,...,0,일반,1528,NaN,20190413.0,클래식,콘서트홀,100,15,N
11,50.0,F,무료,NaN,NaN,NaN,NaN,NaN,20191005,1417,...,0,K-lang 멤버십 회원(1인2매)20%,315,NaN,20191005.0,오페라,콘서트홀,120,15,Y
16,30.0,F,무료,그린,NaN,NaN,NaN,NaN,20230224,2214,...,0,일반,1684,20230218.0,20230219.0,합창,콘서트홀,100,15,Y
18,70.0,M,골드,무료,NaN,NaN,NaN,NaN,20191220,1106,...,0,골드회원 할인30%,76,20191220.0,20191223.0,클래식,콘서트홀,120,15,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1920834,30.0,F,무료,그린,NaN,NaN,NaN,NaN,20191206,1102,...,0,싹딜가(그린)50%,1170,20191101.0,20191104.0,교향곡,콘서트홀,120,15,Y
1920843,60.0,F,골드,무료,NaN,NaN,NaN,NaN,20181223,1227,...,0,일반,282,NaN,20181202.0,교향곡,콘서트홀,120,15,Y
1920849,30.0,F,무료,NaN,NaN,NaN,NaN,NaN,20230516,1743,...,0,일반,1666,20230317.0,20230318.0,실내악,콘서트홀,85,15,Y
1920855,50.0,M,무료,NaN,NaN,NaN,NaN,NaN,20230522,1729,...,0,일반,2825,20230505.0,20230507.0,교향곡,콘서트홀,120,15,Y
1920864,20.0,F,무료,싹틔우미,NaN,NaN,NaN,NaN,20221224,1223,...,0,청소년(만7세~만24세/본인만)30%,313,NaN,20221223.0,교향곡,콘서트홀,120,0,Y

In [9]:
#공연시작시간cthall['time'] = 'morning'
cthall['time'] = 'morning'
cthall.loc[cthall['tran_time']>=1200,'time'] = 'afternoon'
cthall.loc[cthall['tran_time']>=1800,'time'] = 'evening'

C:\Users\Admin\AppData\Local\Temp\ipykernel_25084\2521578884.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cthall['time'] = 'morning'

In [10]:
cthall['floor'] = cthall['seat'].str.split(' ').str[0]
cthall['zone'] = cthall['seat'].str.split(' ').str[1].str[:3]
cthall['col'] = cthall['seat'].str.split(' ').str[1].str[3:]

C:\Users\Admin\AppData\Local\Temp\ipykernel_25084\3041266885.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cthall['floor'] = cthall['seat'].str.split(' ').str[0]
C:\Users\Admin\AppData\Local\Temp\ipykernel_25084\3041266885.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cthall['zone'] = cthall['seat'].str.split(' ').str[1].str[:3]
C:\Users\Admin\AppData\Local\Temp\ipykernel_25084\3041266885.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cthall['col'] = cthall['seat'].str.split(' ').str[1].str[3:]

In [11]:
# discount_type 전처리
#새로운 column
# - column명 : discount
# - %앞의 숫자 : %앞의 수
# - 2+1 : -21
# - 결츨값 : -10
cthall['discount'] = cthall['discount_type'].str.extract('([0-9]+)\%')

cthall.loc[(~cthall['discount_type'].str.contains('%')) & (cthall['discount_type'].str.contains('특별할인')) & \
           (~(cthall['discount_type'].str.contains('기획사'))),'discount'] = -21

cthall['discount'] = cthall['discount'].fillna('-10')

C:\Users\Admin\AppData\Local\Temp\ipykernel_25084\2087859664.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cthall['discount'] = cthall['discount_type'].str.extract('([0-9]+)\%')
C:\Users\Admin\AppData\Local\Temp\ipykernel_25084\2087859664.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cthall['discount'] = cthall['discount'].fillna('-10')

In [12]:
# discount를 사용하여 원가격복구
# - discount가 숫자
#   - 역수를 사용하여 원가격으로 복구
# - discount가 투플원
#   - 기존가격의 2/3 
cthall[cthall['discount']==-21][['performance_code','discount','price']].sort_values(['performance_code','price'])

         performance_code discount  price
84003                1283      -21  25000
104192               1283      -21  25000
263957               1283      -21  25000
733908               1283      -21  25000
818118               1283      -21  25000
1014441              1283      -21  25000
1328036              1283      -21  25000
1544147              1283      -21  25000
1546098              1283      -21  25000
1705943              1283      -21  25000
1731620              1283      -21  25000
1869452              1283      -21  25000
256113               1283      -21  40000
560839               1283      -21  40000
586267               1283      -21  40000
609560               1283      -21  40000
753183               1283      -21  40000
1061288              1283      -21  40000
1398324              1283      -21  40000
1518512              1283      -21  40000
1631046              1283      -21  40000
134162               1284      -21  40000
718438               1284      -21  40000
1812714              1284      -21  40000
1620285              1285      -21  25000
1833029              1285      -21  25000
1874601              1285      -21  25000
784808               1286      -21  25000
805119               1286      -21  25000
1280837              1286      -21  25000
259426               1286      -21  40000
583428               1286      -21  40000
1526052              1286      -21  40000

In [13]:
#discoount 정수형으로 변경
cthall['discount'].astype(int)

4         -10
9         -10
11         20
16        -10
18         30
           ..
1920834    50
1920843   -10
1920849   -10
1920855   -10
1920864    30
Name: discount, Length: 315158, dtype: int32

In [14]:
# 원가격 복구를 위한 함수
from fractions import Fraction # 분수 표현식
import numpy as np
def ori_price(df):
    if df["discount"] == -10:
        return df['price']
    elif df["discount"] == -21:
        return df['price'] * float(Fraction(2, 3))
    else:
        return df['price'] *np.reciprocal(1-(int(df["discount"])/100))

In [15]:
#원가격복구
cthall['ori_price'] = cthall.apply(ori_price , axis=1)

C:\Users\Admin\AppData\Local\Temp\ipykernel_25084\300973812.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cthall['ori_price'] = cthall.apply(ori_price , axis=1)

In [16]:
# datediff 생성

cthall['date_diff'] = np.where( cthall['tran_date'] == cthall['pre_open_date'] , 0 , cthall['tran_date'] - cthall['pre_open_date'])
cthall['date_diff'].fillna( (cthall['tran_date'] - cthall['open_date'] ), inplace=True )

C:\Users\Admin\AppData\Local\Temp\ipykernel_25084\612837892.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cthall['date_diff'] = np.where( cthall['tran_date'] == cthall['pre_open_date'] , 0 , cthall['tran_date'] - cthall['pre_open_date'])
C:\Users\Admin\AppData\Local\Temp\ipykernel_25084\612837892.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cthall['date_diff'].fillna( (cthall['tran_date'] - cthall['open_date'] ), inplace=True )

In [17]:
# 코로나 사회적거리두기기간에 코로나단계 파생변수 생성
# 코로나 사회적거리두기기간 20200322 ~ 20220418
def sep_social_d(date_a,date_b, level):
    a = df_covid.query( (" {} <= tran_date <= {} ").format(date_a , date_b) )
    a['covid_social_sep_level'] = level
    return a

In [20]:
def covid_sep(df):
    if 20200816<= df["tran_date"] <= 20200829 :
        return 2
    elif 20200830<= df["tran_date"] <= 20200913:
        return 2.5
    elif 20200914<= df["tran_date"] <=20200927 :
        return 2
    elif 20201012<= df["tran_date"] <=20201123 :
        return 1
    elif 20201124<= df["tran_date"] <=20201207 :
        return 2
    elif 20201208<= df["tran_date"] <=20210214 :
        return 2.5
    elif 20210215<= df["tran_date"] <=20210614 :
        return 2
    elif 20210712<= df["tran_date"] <=20211003 :
        return 4
    else:
        return 0

In [21]:
cthall['covid_sep'] = cthall.apply(covid_sep, axis=1)

C:\Users\Admin\AppData\Local\Temp\ipykernel_25084\585653982.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cthall['covid_sep'] = cthall.apply(covid_sep, axis=1)

In [22]:
cthall = cthall.drop(['age', 'gender','membership_type_1', 'membership_type_2','membership_type_3',\
                      'membership_type_4','membership_type_5', 'membership_type_6','ticket_cancel',\
                      'discount_type','place', 'play_st_time','intermission', 'discount'], axis=1)
#ticket_cancel과 discount_type은 원데이터 전처리에서 컬럼제거를 할 것인가?

In [23]:
cthall.to_csv("./merge_cutrow")